pages:
  stage: deploy
  image: python:3.12-slim
  script:
    - pip install mkdocs-material pymdown-extensions
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  only:
    - main
